# Generated by Django 4.2.6 on 2023-10-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
    ]
