# Generated by Django 4.2.6 on 2023-10-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_supplierstockitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierstockitem",
            name="price_per_one",
            field=models.PositiveBigIntegerField(),
        ),
    ]
