# Generated by Django 4.2.5 on 2023-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealermarketingcampaign",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suppliermarketingcampaign",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dealerdiscount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dealerdiscount",
            name="percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="dealermarketingcampaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="supplierdiscount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="supplierdiscount",
            name="percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="suppliermarketingcampaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
