# Generated by Django 4.2.5 on 2023-09-23 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dealers", "0002_alter_dealer_is_active_remove_dealerstockitem_car_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="user_profile",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
