# Generated by Django 4.2.6 on 2023-10-16 11:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0005_alter_dealerstockitem_price_per_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealer",
            name="place",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
