# Generated by Django 4.2.5 on 2023-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=255)),
                (
                    "model",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "generation",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("release_year", models.DateField(max_length=255)),
                (
                    "end_of_production_year",
                    models.DateField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("generation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "release_year",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
                (
                    "end_of_production_year",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
