# Generated by Django 4.2.5 on 2023-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carcharacteristic",
            old_name="model",
            new_name="car_model",
        ),
        migrations.RemoveField(
            model_name="car",
            name="end_of_production_year",
        ),
        migrations.RemoveField(
            model_name="car",
            name="model",
        ),
        migrations.RemoveField(
            model_name="car",
            name="release_year",
        ),
        migrations.RemoveField(
            model_name="carcharacteristic",
            name="end_of_production_year",
        ),
        migrations.RemoveField(
            model_name="carcharacteristic",
            name="release_year",
        ),
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="year_end_of_production",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="year_release",
            field=models.PositiveSmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carcharacteristic",
            name="year_end_of_production",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carcharacteristic",
            name="year_release",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="generation",
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="carcharacteristic",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
