# Generated by Django 4.2.5 on 2023-09-05 10:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("balance", models.PositiveBigIntegerField(default=0)),
                ("place", django_countries.fields.CountryField(max_length=2)),
                ("cars", models.ManyToManyField(to="cars.car")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
