# Generated by Django 4.2.5 on 2023-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
