# Generated by Django 4.2.6 on 2023-10-16 11:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="place",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
