# Generated by Django 4.2.5 on 2023-09-19 09:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_is_active"),
        ("suppliers", "0002_alter_supplier_is_active_and_more"),
        ("dealers", "0002_alter_dealer_is_active_remove_dealerstockitem_car_and_more"),
        ("cars", "0002_rename_model_carcharacteristic_car_model_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeroffer",
            name="bought_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="customeroffer",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers_offers",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="customeroffer",
            name="car_price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customeroffer",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customeroffer",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="customerdealshistory",
            name="car",
        ),
        migrations.RemoveField(
            model_name="customerdealshistory",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerdealshistory",
            name="dealer",
        ),
        migrations.AlterField(
            model_name="customerdealshistory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customeroffer",
            name="characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cars.carcharacteristic",
            ),
        ),
        migrations.AlterField(
            model_name="customeroffer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="dealerdealshistory",
            name="car",
        ),
        migrations.RemoveField(
            model_name="dealerdealshistory",
            name="dealer",
        ),
        migrations.AlterField(
            model_name="dealerdealshistory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="dealerdealshistory",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="totaldealerpurchase",
            name="customer",
        ),
        migrations.AlterField(
            model_name="totaldealerpurchase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="totalsupplierpurchase",
            name="dealer",
        ),
        migrations.AlterField(
            model_name="totalsupplierpurchase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="DealerOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_price", models.PositiveBigIntegerField()),
                (
                    "place",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("car_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField()),
                (
                    "bought_car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.car",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealers_offers",
                        to="cars.car",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dealers.dealer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customerdealshistory",
            name="car",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="cars.car"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerdealshistory",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="customers.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerdealshistory",
            name="dealer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_history",
                to="dealers.dealer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealerdealshistory",
            name="car",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="cars.car"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealerdealshistory",
            name="dealer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="dealers.dealer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealerdealshistory",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_history",
                to="suppliers.supplier",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="totaldealerpurchase",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="total_purchases",
                to="customers.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="totalsupplierpurchase",
            name="dealer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_history",
                to="dealers.dealer",
            ),
            preserve_default=False,
        ),
    ]
